apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  selector:
    matchLabels:
      app: expiration
  replicas: 1
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: yash02092003/expiration
          env:
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: REDIS_PORT
              value: "6379"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'